import type {
  ActivityEvent,
  ExceptionItem,
  LanguageRule,
  Person,
  PromptVersion,
  RequestItem,
  Segment,
  Stage,
  TaskItem,
  TermCandidate,
  TermEntry,
  TmEntry,
} from "./types";

export const LANGUAGE_META = {
  zh: { label: "Chinese (Simplified)", short: "ZH", token: "text-lang-zh", bg: "bg-lang-zh" },
  en: { label: "English (master)", short: "EN", token: "text-lang-en", bg: "bg-lang-en" },
  ja: { label: "Japanese", short: "JA", token: "text-lang-ja", bg: "bg-lang-ja" },
  de: { label: "German", short: "DE", token: "text-lang-de", bg: "bg-lang-de" },
  fr: { label: "French", short: "FR", token: "text-lang-fr", bg: "bg-lang-fr" },
} as const;

export const requests: RequestItem[] = [
  {
    id: "REQ-2418",
    title: "Smart Ledger launch — in-product strings & campaign message",
    requester: "Wen Jiang",
    team: "Product",
    risk: "standard",
    due: "2026-08-06",
    languages: ["en", "ja", "de", "fr"],
    segmentCount: 8,
    status: "blocked",
    progress: 62,
    summary:
      "Feature launch bundle: onboarding UI copy plus one marketing message. Chinese source approved by the product team on Jul 28.",
  },
  {
    id: "REQ-2410",
    title: "Billing settings — error state copy",
    requester: "Alicia Moreau",
    team: "Operations",
    risk: "standard",
    due: "2026-08-03",
    languages: ["en", "ja", "de", "fr"],
    segmentCount: 14,
    status: "in-progress",
    progress: 48,
    summary: "Routine string refresh for the billing settings surface.",
  },
  {
    id: "REQ-2402",
    title: "Data residency notice (regulated)",
    requester: "Hannah Reuter",
    team: "Legal & Compliance",
    risk: "high",
    due: "2026-08-11",
    languages: ["en", "de", "fr"],
    segmentCount: 6,
    status: "queued",
    progress: 12,
    summary: "High-risk content. Second approver rule applies when enabled in Settings.",
  },
  {
    id: "REQ-2395",
    title: "July release notes",
    requester: "Marco Silva",
    team: "Marketing",
    risk: "standard",
    due: "2026-07-28",
    languages: ["en", "ja", "de", "fr"],
    segmentCount: 22,
    status: "released",
    progress: 100,
    summary: "Released to all four locales on Jul 28.",
  },
];

export const ACTIVE_REQUEST_ID = "REQ-2418";

export const stages: Stage[] = [
  {
    id: "source-qa",
    name: "Source QA",
    description: "Chinese source is checked for clarity, placeholders and completeness before anything is generated.",
    status: "blocked",
    owner: "Automated + Requester",
    startedAt: "Jul 29, 09:12",
    checks: [
      { id: "c1", category: "source-clarity", label: "Ambiguity scan", state: "fail", detail: "1 sentence has two possible readings.", scope: "8 segments" },
      { id: "c2", category: "variables", label: "Placeholder integrity", state: "pass", detail: "All 6 placeholders well formed.", scope: "8 segments" },
      { id: "c3", category: "missing-content", label: "Completeness", state: "pass", detail: "No empty source strings.", scope: "8 segments" },
      { id: "c4", category: "terminology", label: "Source term consistency", state: "warn", detail: "‘智能账本’ appears with two capitalisation styles.", scope: "3 segments" },
    ],
  },
  {
    id: "english-master",
    name: "English master",
    description: "One approved English master is produced and locked; every other language derives from it.",
    status: "done",
    owner: "Ivy Chen · Language Owner (EN)",
    startedAt: "Jul 29, 11:40",
    completedAt: "Jul 30, 08:05",
    checks: [
      { id: "c5", category: "terminology", label: "Glossary alignment", state: "pass", detail: "12/12 approved terms matched.", scope: "8 segments" },
      { id: "c6", category: "numbers", label: "Numbers & currency", state: "pass", detail: "3 numeric tokens preserved.", scope: "8 segments" },
      { id: "c7", category: "release-readiness", label: "Master lock", state: "pass", detail: "Master approved and locked at v1.2.", scope: "Request" },
    ],
  },
  {
    id: "generation",
    name: "Multilingual generation",
    description: "JA, DE and FR are generated from the English master using the active prompt version and translation memory.",
    status: "done",
    owner: "Automated",
    startedAt: "Jul 30, 08:12",
    completedAt: "Jul 30, 08:19",
    checks: [
      { id: "c8", category: "terminology", label: "TM reuse", state: "pass", detail: "9 segments matched memory at ≥85%.", scope: "24 translations" },
      { id: "c9", category: "variables", label: "Placeholder carry-over", state: "pass", detail: "18/18 placeholders preserved.", scope: "24 translations" },
    ],
  },
  {
    id: "language-qa",
    name: "Language QA",
    description: "Per-language checks run automatically: terminology, numbers, variables, limits, formatting and locale rules.",
    status: "blocked",
    owner: "Automated",
    startedAt: "Jul 30, 08:20",
    checks: [
      { id: "c10", category: "locale-rules", label: "JA formality register", state: "fail", detail: "Segment uses plain form where です・ます is required.", scope: "Japanese" },
      { id: "c11", category: "character-limit", label: "DE UI length", state: "fail", detail: "Button label is 27/20 characters.", scope: "German" },
      { id: "c12", category: "formatting", label: "FR spacing & punctuation", state: "pass", detail: "Narrow no-break spaces correct.", scope: "French" },
      { id: "c13", category: "numbers", label: "Decimal separators", state: "pass", detail: "Locale separators applied.", scope: "JA · DE · FR" },
      { id: "c14", category: "missing-content", label: "Coverage", state: "pass", detail: "24/24 translations present.", scope: "All targets" },
    ],
  },
  {
    id: "exceptions",
    name: "Human exceptions",
    description: "Only failed checks reach a person. One Language Owner decides; a second approver appears only when configured.",
    status: "active",
    owner: "Language Owners",
    startedAt: "Jul 30, 08:24",
    checks: [
      { id: "c15", category: "locale-rules", label: "JA formality exception", state: "pending", detail: "Awaiting Kenji Sato.", scope: "1 segment" },
      { id: "c16", category: "character-limit", label: "DE length exception", state: "pending", detail: "Awaiting Lukas Brandt.", scope: "1 segment" },
      { id: "c17", category: "source-clarity", label: "Source clarification", state: "pending", detail: "Awaiting requester reply.", scope: "1 segment" },
    ],
  },
  {
    id: "release",
    name: "Release",
    description: "Release readiness is re-checked at the moment of publication, not before the exceptions clear.",
    status: "waiting",
    owner: "Automated",
    checks: [
      { id: "c18", category: "release-readiness", label: "All exceptions closed", state: "pending", detail: "3 open exceptions.", scope: "Request" },
      { id: "c19", category: "release-readiness", label: "Locked master unchanged", state: "pending", detail: "Re-verified at publish time.", scope: "Request" },
    ],
  },
  {
    id: "knowledge",
    name: "Knowledge updates",
    description: "Repeated human edits become terminology and memory candidates, scoped before they change anything global.",
    status: "queued",
    owner: "Platform Admin",
    checks: [
      { id: "c20", category: "terminology", label: "Candidate review", state: "pending", detail: "1 candidate awaiting scope decision.", scope: "Campaign" },
    ],
  },
];

export const segments: Segment[] = [
  {
    id: "SEG-01",
    key: "onboarding.title",
    kind: "ui-string",
    context: "Onboarding screen heading",
    charLimit: 32,
    source: "欢迎使用智能账本",
    english: "Welcome to Smart Ledger",
    targets: {
      ja: { value: "スマート台帳へようこそ", state: "clean" },
      de: { value: "Willkommen bei Smart Ledger", state: "clean", charCount: 27, charLimit: 32 },
      fr: { value: "Bienvenue dans Smart Ledger", state: "clean" },
    },
  },
  {
    id: "SEG-02",
    key: "onboarding.cta",
    kind: "ui-string",
    context: "Primary button, fixed width",
    charLimit: 20,
    source: "立即开始",
    english: "Get started",
    targets: {
      ja: { value: "今すぐ開始", state: "clean" },
      de: {
        value: "Jetzt mit der Einrichtung beginnen",
        state: "flagged",
        charCount: 34,
        charLimit: 20,
        note: "Exceeds the 20-character button limit by 14 characters.",
      },
      fr: { value: "Commencer", state: "clean" },
    },
  },
  {
    id: "SEG-03",
    key: "onboarding.hint",
    kind: "ui-string",
    context: "Helper text under the account field",
    source: "请先绑定您的对公账户，稍后可在设置中修改。",
    english: "Link your corporate account first — you can change it later in Settings.",
    targets: {
      ja: {
        value: "先に法人口座を連携して。設定で後から変更できる。",
        state: "flagged",
        note: "Plain form used where the JA style guide requires です・ます.",
      },
      de: { value: "Verknüpfen Sie zuerst Ihr Firmenkonto — Änderung später in den Einstellungen möglich.", state: "clean" },
      fr: { value: "Associez d’abord votre compte professionnel — modifiable ensuite dans les Paramètres.", state: "clean" },
    },
  },
  {
    id: "SEG-04",
    key: "ledger.summary",
    kind: "ui-string",
    context: "Summary line with a variable",
    source: "本月已同步 {count} 笔交易",
    english: "{count} transactions synced this month",
    targets: {
      ja: { value: "今月は {count} 件の取引を同期しました", state: "clean" },
      de: { value: "{count} Transaktionen in diesem Monat synchronisiert", state: "clean" },
      fr: { value: "{count} transactions synchronisées ce mois-ci", state: "clean" },
    },
  },
  {
    id: "SEG-05",
    key: "ledger.ambiguous",
    kind: "ui-string",
    context: "Status message shown after a sync run",
    source: "系统将在同步完成后自动关闭该账本记录。",
    english: "—",
    targets: {
      ja: { value: "—", state: "pending" },
      de: { value: "—", state: "pending" },
      fr: { value: "—", state: "pending" },
    },
  },
  {
    id: "SEG-06",
    key: "marketing.headline",
    kind: "marketing",
    context: "Campaign email headline",
    source: "让每一笔账都清清楚楚",
    english: "Make every entry accountable",
    targets: {
      ja: { value: "すべての記帳を、明確に。", state: "clean" },
      de: { value: "Jede Buchung nachvollziehbar machen", state: "clean" },
      fr: { value: "Rendre chaque écriture traçable", state: "clean" },
    },
  },
  {
    id: "SEG-07",
    key: "marketing.body",
    kind: "marketing",
    context: "Campaign email body",
    source: "智能账本自动归集凭证，减少月末对账的重复工作。",
    english: "Smart Ledger collects vouchers automatically and cuts repetitive month-end reconciliation work.",
    targets: {
      ja: { value: "スマート台帳は証憑を自動で集約し、月末照合の反復作業を減らします。", state: "clean" },
      de: { value: "Smart Ledger sammelt Belege automatisch und reduziert wiederkehrende Abstimmungsarbeit zum Monatsende.", state: "clean" },
      fr: { value: "Smart Ledger regroupe automatiquement les justificatifs et réduit le travail répétitif de rapprochement de fin de mois.", state: "clean" },
    },
  },
  {
    id: "SEG-08",
    key: "marketing.cta",
    kind: "marketing",
    context: "Campaign email button",
    charLimit: 24,
    source: "查看对账中心",
    english: "Open the reconciliation hub",
    targets: {
      ja: { value: "照合センターを見る", state: "clean" },
      de: { value: "Zum Abstimmungscenter", state: "clean", charCount: 22, charLimit: 24 },
      fr: { value: "Ouvrir le centre de rapprochement", state: "clean" },
    },
  },
];

export const exceptions: ExceptionItem[] = [
  {
    id: "EXC-01",
    kind: "source-clarity",
    language: "zh",
    segmentId: "SEG-05",
    title: "Ambiguous Chinese source sentence",
    summary:
      "“系统将在同步完成后自动关闭该账本记录。” can mean the ledger record is closed (finalised) or the record view is dismissed. Generation is held for this segment only.",
    severity: "blocked",
    assignee: "Wen Jiang · Requester",
    raisedAt: "Jul 29, 09:14",
    automation: {
      trigger: "Source QA · ambiguity scan",
      rule: "SRC-04 — a sentence with more than one plausible object reading is returned to the requester",
      evidence: "Two candidate readings scored within 0.06 of each other; ‘关闭’ maps to both close and dismiss in memory.",
      reversible: true,
    },
    suggestion:
      "Requester clarification: “The system finalises the ledger record automatically once the sync completes.”",
    resolutionLabel: "Accept clarification & resume",
    rejectLabel: "Send back to requester",
    state: "open",
  },
  {
    id: "EXC-02",
    kind: "locale-rules",
    language: "ja",
    segmentId: "SEG-03",
    title: "Japanese fails the formality rule",
    summary:
      "The helper text uses plain form (連携して / 変更できる) where the Japanese style guide requires です・ます throughout product surfaces.",
    severity: "blocked",
    assignee: "Kenji Sato · Language Owner (JA)",
    raisedAt: "Jul 30, 08:21",
    automation: {
      trigger: "Language QA · locale rules",
      rule: "JA-FORMALITY-01 — product UI must use です・ます register",
      evidence: "2 clause endings detected in plain form; rule severity is blocking for UI strings.",
      reversible: true,
    },
    suggestion: "先に法人口座を連携してください。設定で後から変更できます。",
    resolutionLabel: "Apply suggested register",
    rejectLabel: "Keep current & log exception",
    state: "open",
  },
  {
    id: "EXC-03",
    kind: "character-limit",
    language: "de",
    segmentId: "SEG-02",
    title: "German exceeds the UI character limit",
    summary:
      "The onboarding button renders at a fixed width. The German output is 34 characters against a 20-character limit and would truncate.",
    severity: "blocked",
    assignee: "Lukas Brandt · Language Owner (DE)",
    raisedAt: "Jul 30, 08:22",
    automation: {
      trigger: "Language QA · character limit",
      rule: "UI-LEN-02 — output must fit the declared limit for the component",
      evidence: "34 / 20 characters. Limit read from the string metadata supplied with the request.",
      reversible: true,
    },
    suggestion: "Jetzt starten",
    resolutionLabel: "Apply shorter variant",
    rejectLabel: "Request a wider component",
    state: "open",
  },
  {
    id: "EXC-04",
    kind: "capacity",
    language: "fr",
    title: "Language Owner over capacity — task reassigned",
    summary:
      "Camille Roux was at 118% of weekly capacity. One French review task that had not started was moved to Élodie Bernard, who shares the same language scope.",
    severity: "warn",
    assignee: "Operations · automated",
    raisedAt: "Jul 30, 09:02",
    automation: {
      trigger: "Operations · capacity balancing",
      rule: "OPS-CAP-03 — reassign unstarted tasks when an owner exceeds 110% capacity and an equally scoped owner is below 85%",
      evidence: "Camille 118% (26/22h) · Élodie 71% (17/24h). Task TSK-19 had no recorded work.",
      reversible: true,
    },
    suggestion: "Keep the reassignment to Élodie Bernard.",
    resolutionLabel: "Confirm reassignment",
    rejectLabel: "Undo & return to Camille",
    state: "open",
  },
  {
    id: "EXC-05",
    kind: "terminology",
    language: "de",
    title: "Repeated edits produced a terminology candidate",
    summary:
      "‘对账中心’ was manually changed from “Abstimmungscenter” to “Reconciliation Hub” four times in this campaign. The system did not change the global glossary.",
    severity: "warn",
    assignee: "Priya Nair · Platform Admin",
    raisedAt: "Jul 30, 10:15",
    automation: {
      trigger: "Knowledge updates · edit-frequency watcher",
      rule: "KB-TERM-01 — 3+ identical human edits raise a candidate, scoped to the campaign by default",
      evidence: "4 identical edits across 4 segments, all within REQ-2418. No occurrences outside this campaign.",
      reversible: true,
    },
    suggestion: "Keep as a campaign-specific exception for REQ-2418.",
    resolutionLabel: "Scope to this campaign",
    rejectLabel: "Reject candidate",
    state: "open",
  },
];

export const terms: TermEntry[] = [
  { id: "T-01", source: "智能账本", en: "Smart Ledger", ja: "スマート台帳", de: "Smart Ledger", fr: "Smart Ledger", scope: "global", status: "approved", updatedAt: "2026-05-14" },
  { id: "T-02", source: "对公账户", en: "corporate account", ja: "法人口座", de: "Firmenkonto", fr: "compte professionnel", scope: "global", status: "approved", updatedAt: "2026-04-02" },
  { id: "T-03", source: "对账中心", en: "reconciliation hub", ja: "照合センター", de: "Abstimmungscenter", fr: "centre de rapprochement", scope: "global", status: "approved", updatedAt: "2026-03-19" },
  { id: "T-04", source: "凭证", en: "voucher", ja: "証憑", de: "Beleg", fr: "justificatif", scope: "global", status: "approved", updatedAt: "2026-02-08" },
  { id: "T-05", source: "同步", en: "sync", ja: "同期", de: "Synchronisierung", fr: "synchronisation", scope: "global", status: "approved", updatedAt: "2026-01-27" },
];

export const tmEntries: TmEntry[] = [
  { id: "TM-01", source: "立即开始", target: "今すぐ開始", language: "ja", match: 100, lastUsed: "2026-07-30" },
  { id: "TM-02", source: "立即开始", target: "Commencer", language: "fr", match: 100, lastUsed: "2026-07-30" },
  { id: "TM-03", source: "本月已同步 {count} 笔交易", target: "{count} Transaktionen in diesem Monat synchronisiert", language: "de", match: 92, lastUsed: "2026-07-30" },
  { id: "TM-04", source: "欢迎使用智能账本", target: "スマート台帳へようこそ", language: "ja", match: 88, lastUsed: "2026-07-29" },
  { id: "TM-05", source: "查看对账中心", target: "Ouvrir le centre de rapprochement", language: "fr", match: 85, lastUsed: "2026-07-30" },
];

export const languageRules: LanguageRule[] = [
  { id: "R-01", language: "ja", name: "です・ます register", description: "Product UI and helper text must use polite form.", severity: "blocked", enabled: true },
  { id: "R-02", language: "ja", name: "Full-width punctuation", description: "Use 、and 。 in running text.", severity: "warn", enabled: true },
  { id: "R-03", language: "de", name: "UI length budget", description: "Output must fit the declared component character limit.", severity: "blocked", enabled: true },
  { id: "R-04", language: "de", name: "Formal address (Sie)", description: "Address the reader with Sie in all product copy.", severity: "blocked", enabled: true },
  { id: "R-05", language: "fr", name: "Narrow no-break space", description: "Required before : ; ! ?", severity: "warn", enabled: true },
  { id: "R-06", language: "en", name: "Sentence case headings", description: "Headings use sentence case, not title case.", severity: "warn", enabled: true },
];

export const promptVersions: PromptVersion[] = [
  { id: "P-01", name: "EN master drafting", version: "v4.2", language: "en", status: "active", changedAt: "2026-06-30", change: "Added instruction to preserve placeholder order." },
  { id: "P-02", name: "JA generation", version: "v3.8", language: "ja", status: "active", changedAt: "2026-07-11", change: "Register guidance strengthened for helper text." },
  { id: "P-03", name: "DE generation", version: "v3.9", language: "de", status: "active", changedAt: "2026-07-18", change: "Length-aware phrasing for constrained components." },
  { id: "P-04", name: "DE generation", version: "v4.0", language: "de", status: "trial", changedAt: "2026-07-30", change: "Trial: prefers compound-free short forms under 20 characters." },
  { id: "P-05", name: "FR generation", version: "v3.5", language: "fr", status: "active", changedAt: "2026-05-22", change: "Typographic spacing rules added." },
];

export const people: Person[] = [
  { id: "U-01", name: "Ivy Chen", role: "Language Owner (EN)", languages: ["en"], capacity: 24, load: 14, timezone: "UTC+8" },
  { id: "U-02", name: "Kenji Sato", role: "Language Owner (JA)", languages: ["ja"], capacity: 22, load: 19, timezone: "UTC+9" },
  { id: "U-03", name: "Lukas Brandt", role: "Language Owner (DE)", languages: ["de"], capacity: 24, load: 20, timezone: "UTC+2" },
  { id: "U-04", name: "Camille Roux", role: "Language Owner (FR)", languages: ["fr"], capacity: 22, load: 26, timezone: "UTC+2" },
  { id: "U-05", name: "Élodie Bernard", role: "Language Owner (FR)", languages: ["fr"], capacity: 24, load: 17, timezone: "UTC+1" },
  { id: "U-06", name: "Priya Nair", role: "Platform Admin", languages: ["en", "ja", "de", "fr"], capacity: 20, load: 9, timezone: "UTC+5:30" },
];

export const tasks: TaskItem[] = [
  { id: "TSK-11", name: "English master review", language: "en", assignee: "Ivy Chen", due: "Jul 30", state: "done", slaRisk: "none", hours: 3 },
  { id: "TSK-14", name: "JA exception review", language: "ja", assignee: "Kenji Sato", due: "Aug 1", state: "in-progress", slaRisk: "at-risk", hours: 2 },
  { id: "TSK-16", name: "DE exception review", language: "de", assignee: "Lukas Brandt", due: "Aug 1", state: "in-progress", slaRisk: "none", hours: 2 },
  { id: "TSK-19", name: "FR final read", language: "fr", assignee: "Élodie Bernard", due: "Aug 3", state: "reassigned", slaRisk: "none", hours: 4 },
  { id: "TSK-21", name: "Source clarification follow-up", language: "zh", assignee: "Wen Jiang", due: "Jul 31", state: "not-started", slaRisk: "breached", hours: 1 },
  { id: "TSK-24", name: "Release readiness sweep", language: "en", assignee: "Priya Nair", due: "Aug 5", state: "not-started", slaRisk: "none", hours: 1 },
];

export const termCandidates: TermCandidate[] = [
  {
    id: "TC-01",
    source: "对账中心",
    currentTarget: "Abstimmungscenter",
    proposedTarget: "Reconciliation Hub",
    language: "de",
    editCount: 4,
    evidenceSegments: ["SEG-08", "SEG-07", "SEG-06", "SEG-04"],
    scopeSuggestion: "campaign",
    rationale:
      "The launch campaign uses the English product-surface name. Outside this campaign the approved German term is still correct, so the candidate stays campaign-scoped unless an admin promotes it.",
    state: "pending",
    automation: {
      trigger: "Edit-frequency watcher",
      rule: "KB-TERM-01 — 3+ identical human edits raise a candidate",
      evidence: "4 identical edits inside REQ-2418; 0 occurrences elsewhere in the last 90 days.",
      reversible: true,
    },
  },
  {
    id: "TC-02",
    source: "同步完成",
    currentTarget: "同期が完了しました",
    proposedTarget: "同期完了",
    language: "ja",
    editCount: 3,
    evidenceSegments: ["SEG-04", "SEG-05", "SEG-01"],
    scopeSuggestion: "campaign",
    rationale: "Shorter form preferred in constrained status rows. Not yet observed in long-form content.",
    state: "pending",
    automation: {
      trigger: "Edit-frequency watcher",
      rule: "KB-TERM-01 — 3+ identical human edits raise a candidate",
      evidence: "3 identical edits across 3 status-row segments.",
      reversible: true,
    },
  },
];

export const initialActivity: ActivityEvent[] = [
  {
    id: "A-05",
    at: "Jul 30, 10:15",
    actor: "Knowledge updates",
    actorType: "system",
    message: "Terminology candidate raised for ‘对账中心’ (DE)",
    reason: "KB-TERM-01 · 4 identical human edits inside REQ-2418. Global glossary unchanged.",
    reversible: true,
  },
  {
    id: "A-04",
    at: "Jul 30, 09:02",
    actor: "Operations",
    actorType: "system",
    message: "TSK-19 reassigned from Camille Roux to Élodie Bernard",
    reason: "OPS-CAP-03 · Camille at 118% capacity, Élodie at 71%. Task had not started.",
    reversible: true,
  },
  {
    id: "A-03",
    at: "Jul 30, 08:22",
    actor: "Language QA",
    actorType: "system",
    message: "German button label blocked on character limit (34/20)",
    reason: "UI-LEN-02 · limit declared in the string metadata.",
    reversible: true,
  },
  {
    id: "A-02",
    at: "Jul 30, 08:21",
    actor: "Language QA",
    actorType: "system",
    message: "Japanese helper text blocked on formality rule",
    reason: "JA-FORMALITY-01 · plain form detected in a product UI string.",
    reversible: true,
  },
  {
    id: "A-01",
    at: "Jul 29, 09:14",
    actor: "Source QA",
    actorType: "system",
    message: "Ambiguous Chinese sentence returned to the requester",
    reason: "SRC-04 · two plausible readings within 0.06 confidence.",
    reversible: true,
  },
];
