/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as ProductRouteImport } from './routes/product'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAssetsRouteImport } from './routes/app.assets'
import { Route as AppEditorRouteImport } from './routes/app.editor'
import { Route as AppGuidedRouteImport } from './routes/app.guided'
import { Route as AppKnowledgeRouteImport } from './routes/app.knowledge'
import { Route as AppOperationsRouteImport } from './routes/app.operations'
import { Route as AppRequestsRouteImport } from './routes/app.requests'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppWorkflowRouteImport } from './routes/app.workflow'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorRoute = AppEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AppRoute,
} as any)
const AppGuidedRoute = AppGuidedRouteImport.update({
  id: '/guided',
  path: '/guided',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppOperationsRoute = AppOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowRoute = AppWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/decisions': typeof DecisionsRoute
  '/product': typeof ProductRoute
  '/roles': typeof RolesRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/editor': typeof AppEditorRoute
  '/app/guided': typeof AppGuidedRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/operations': typeof AppOperationsRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/workflow': typeof AppWorkflowRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decisions': typeof DecisionsRoute
  '/product': typeof ProductRoute
  '/roles': typeof RolesRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/editor': typeof AppEditorRoute
  '/app/guided': typeof AppGuidedRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/operations': typeof AppOperationsRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/workflow': typeof AppWorkflowRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/decisions': typeof DecisionsRoute
  '/product': typeof ProductRoute
  '/roles': typeof RolesRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/editor': typeof AppEditorRoute
  '/app/guided': typeof AppGuidedRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/operations': typeof AppOperationsRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/workflow': typeof AppWorkflowRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/decisions'
    | '/product'
    | '/roles'
    | '/app/analytics'
    | '/app/assets'
    | '/app/editor'
    | '/app/guided'
    | '/app/knowledge'
    | '/app/operations'
    | '/app/requests'
    | '/app/settings'
    | '/app/workflow'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/decisions'
    | '/product'
    | '/roles'
    | '/app/analytics'
    | '/app/assets'
    | '/app/editor'
    | '/app/guided'
    | '/app/knowledge'
    | '/app/operations'
    | '/app/requests'
    | '/app/settings'
    | '/app/workflow'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/decisions'
    | '/product'
    | '/roles'
    | '/app/analytics'
    | '/app/assets'
    | '/app/editor'
    | '/app/guided'
    | '/app/knowledge'
    | '/app/operations'
    | '/app/requests'
    | '/app/settings'
    | '/app/workflow'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DecisionsRoute: typeof DecisionsRoute
  ProductRoute: typeof ProductRoute
  RolesRoute: typeof RolesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets': {
      id: '/app/assets'
      path: '/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor': {
      id: '/app/editor'
      path: '/editor'
      fullPath: '/app/editor'
      preLoaderRoute: typeof AppEditorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/guided': {
      id: '/app/guided'
      path: '/guided'
      fullPath: '/app/guided'
      preLoaderRoute: typeof AppGuidedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/operations': {
      id: '/app/operations'
      path: '/operations'
      fullPath: '/app/operations'
      preLoaderRoute: typeof AppOperationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests': {
      id: '/app/requests'
      path: '/requests'
      fullPath: '/app/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workflow': {
      id: '/app/workflow'
      path: '/workflow'
      fullPath: '/app/workflow'
      preLoaderRoute: typeof AppWorkflowRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAssetsRoute: typeof AppAssetsRoute
  AppEditorRoute: typeof AppEditorRoute
  AppGuidedRoute: typeof AppGuidedRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppOperationsRoute: typeof AppOperationsRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorkflowRoute: typeof AppWorkflowRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAssetsRoute: AppAssetsRoute,
  AppEditorRoute: AppEditorRoute,
  AppGuidedRoute: AppGuidedRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppOperationsRoute: AppOperationsRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWorkflowRoute: AppWorkflowRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DecisionsRoute: DecisionsRoute,
  ProductRoute: ProductRoute,
  RolesRoute: RolesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
